# Generated by Django 4.2.5 on 2023-12-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_price_alter_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes_and_colors',
            new_name='sizes_available',
        ),
    ]
