# Generated by Django 4.2.2 on 2023-12-19 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_userdetails_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes_available',
            new_name='available_sizes',
        ),
        migrations.AlterUniqueTogether(
            name='productfororder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productfororder',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(to='core.picture'),
        ),
        migrations.AlterUniqueTogether(
            name='productfororder',
            unique_together={('user', 'product', 'size')},
        ),
        migrations.CreateModel(
            name='ProductOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('related_order', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.RemoveField(
            model_name='productfororder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='productfororder',
            name='color',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='core.productordered'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
