# Generated by Django 4.2.2 on 2023-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_productfororder_user_alter_userdetails_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
