# Generated by Django 4.2.2 on 2024-01-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='tracking_code',
        ),
    ]
