# Generated by Django 4.2.2 on 2024-01-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_products_alter_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
