# Generated by Django 4.2.2 on 2024-01-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_order_stripe_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(max_length=150),
        ),
    ]
